[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"

[dependencies.gtk]
version = "0.15.4"
features = ["v3_24"]

[dependencies.gdk]
version = "0.15.4"
features = ["v3_24"]

[dependencies.gio]
version = "0.15.10"
features = ["v2_60"]

[dependencies.glib]
version = "0.15.10"
features = ["v2_60"]

[dependencies.gettext-rs]
version = "0.7.0"
features = ["gettext-system"]
